spring:
  mvc:
    pathmatch:
#      Настройка для запуска Swagger
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false

topic:
  person-topic: person-event

server:
  port: 8083